# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestApp' do
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestApp

  

  platform :ios, '9.0'
  target 'TestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TestApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestApp-tvOS

  target 'TestApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
